### ISSUE TITLE
[Feature]: 料理ページ (詳細)

### ISSUE THREAD

**Issue by HIMA-HIMAZIN** [wiyco/imap#125]
# Tasks (Features)

TEAM PIPLUP

@duke-imo 

## Overview of Tasks (Features)

タスクの概要

`dishes`ページ

<img width="365" alt="スクリーンショット 2023-09-11 2 47 42" src="https://github.com/wiyco/imap/assets/118464042/cfb463a0-5b8e-4faa-804e-a20446b843b3">

## Todo

想定される作業

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。

**Comment by nafell** [comment]
「ここに行く」ボタンはプライマリアクションなので、[ GO! ]ボタン、[次へ]ボタンと統一したほうが良さげかも？
